name: Automate Docker Image Build & Push to Quay.io Registry CI

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:   
  tests:
    uses: ./.github/workflows/tox-tests.yml
  build:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}
      - uses: actions/checkout@v4
      - name: Get version
        id: getversion
        run: |
          pip install toml
          version=$(cat 'pyproject.toml' | python -c "import toml; import sys; print(toml.loads(sys.stdin.read())['project']['version'])")
          echo "version=$version" >> ${GITHUB_OUTPUT}
      - name: Get commit revision
        id: getrev
        run: echo "::set-output name=rev::$(git rev-parse --short HEAD)"
      - name: Building & Pushing Docker Image
        run: |
          VERSION="${{ steps.getversion.outputs.version }}"
          RELEASE="${{ inputs.release }}"
          REV="${{ steps.getrev.outputs.rev }}"
          FINAL_VERSION=$([ "$RELEASE" = "true" ] && echo "${VERSION}" || echo "${VERSION}-${REV}")
          EXPIRE_LABEL=$([ "$RELEASE" = "true" ] && echo "" || echo "--label quay.expires-after=2d")
          FULL_VERSION="${VERSION}${REV}"
          pip install build
          python -m build
          docker build --build-arg=SDIST="dist/pytractions-${{steps.getversion.outputs.version}}.tar.gz"  -t quay.io/jluza/pytractions:$FINAL_VERSION $EXPIRE_LABEL -f docker/Dockerfile .
          docker push quay.io/jluza/pytractions:$FINAL_VERSION
