name: Automate Docker Image Build & Push to Quay.io Registry CI

on:
  push:
    branches:
      - main

jobs:   
  tests:
    uses: ./.github/workflows/tox-tests.yml
  build:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}
      - uses: actions/checkout@v4
      - name: Get version
        id: getversion
        run: echo "::set-output name=version::$(python setup.py --version)"
      - name: Get commit revision
        id: getrev
        run: echo "::set-output name=rev::$(git rev-parse --short HEAD)"
      - name: Building & Pushing Docker Image
        run: |
          VERSION=${{ steps.getversion.outputs.version }}
          python setup.py sdist
          ls $PWD/
          docker build --build-arg=SDIST="dist/pytractions-${{steps.getversion.outputs.version}}.tar.gz"  -t quay.io/jluza/pytractions:${{ steps.getversion.outputs.version }}-${{ steps.getrev.outputs.rev }} -f docker/Dockerfile .
          docker push quay.io/jluza/pytractions:${{ steps.getversion.outputs.version }}-${{ steps.getrev.outputs.rev }}
